name: Build VITA Filter Injector

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dev deps (PCF)
        working-directory: ./VITAFilterInjector
        run: npm install --no-audit --no-fund


      - name: Build PCF
        working-directory: ./VITAFilterInjector
        env:
          ESLINT_USE_FLAT_CONFIG: "false"
        run: npm run build

      - name: Install PAC (robust)
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          dotnet tool install --global Microsoft.PowerApps.CLI.Tool --version 1.48.2
          echo "$env:USERPROFILE\.dotnet\tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          pac help
          
      # 1) Init solution project (creates solution/ and *.cdsproj)
      - name: Init solution (create cdsproj)
        run: |
          mkdir solution
          cd solution
          pac solution init --publisher-name VITA --publisher-prefix vp
      
      # 2) Add the PCF reference (run INSIDE solution folder)
      - name: Add PCF reference
        working-directory: ./solution
        run: pac solution add-reference --path ../VITAFilterInjector
      
      # 3) Pack unmanaged solution (run INSIDE solution folder)
      - name: Pack unmanaged solution
        working-directory: ./solution
        run: pac solution pack --zipfile ../artifacts/VITA.FilterInjector_unmanaged.zip --folder . --packagetype Unmanaged


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VITA.FilterInjector_unmanaged
          path: artifacts/VITA.FilterInjector_unmanaged.zip
